### ISSUE TITLE
rsync: link_stat "/github/workspace/***@" failed: No such file or directory (2)

### ISSUE THREAD

**Issue by 404-error-404** [AEnterprise/rsync-deploy#4]
Hello.
I have a problem:
```
rsync: link_stat "/github/workspace/***@" failed: No such file or directory (2)
***
***
***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

And my config file is:
```
- name: Deploy to Server
  uses: AEnterprise/rsync-deploy@v1.0
  env:
    DEPLOY_KEY: ${{ secrets.CREATIVE_KEY }} 
    ARGS: -avz --delete --exclude='*.pyc'
    SERVER_PORT: "22"
    FOLDER: ./
    SERVER_IP: ${{ secrets.CREATIVE_HOST }}
    USERNAME: ${{ secrets.CREATIVE_USERNAME }}
    SERVER_DESTINATION: /home/***/***/
```
Although the files will be synced to the server, Github Actions will report an error. Thank you for pay attention to my question!
