### ISSUE TITLE
Error: Unable to resolve action `AEnterprise/rsync-deploy@v1.0.1`, unable to find version `v1.0.1`

### ISSUE THREAD

**Issue by jiangxiaoqiang** [AEnterprise/rsync-deploy#5]
Error: Unable to resolve action `AEnterprise/rsync-deploy@v1.0.1`, unable to find version `v1.0.1`

when I using it in GitHub Actions, show this error:

```
Current runner version: '2.278.0'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `AEnterprise/rsync-deploy@v1.0.1`, unable to find version `v1.0.1`
Retrying in 25.592 seconds
Failed to resolve action download info. Error: Unable to resolve action `AEnterprise/rsync-deploy@v1.0.1`, unable to find version `v1.0.1`
Retrying in 27.781 seconds
Error: Unable to resolve action `AEnterprise/rsync-deploy@v1.0.1`, unable to find version `v1.0.1`


```

this is the script I am using:

```

    - name: Copy jar to Server
      uses: AEnterprise/rsync-deploy@v1.0.1
      env:
        # use pre-configured secret (the private key)
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: -avz --delete
        SERVER_PORT: "22"
        # folder to push (./ is the root of current repo)
        FOLDER: ./dolphin-post/dolphin-post-service/build/libs
        SERVER_IP: ${{ secrets.BINGQIAN_HOST }}
        USERNAME: ${{ secrets.BINGQIAN_USER }}
        SERVER_DESTINATION: /opt/apps/dolphin-post


```

**Comment by lonnieezell** [comment]
@jiangxiaoqiang Did you ever get this resolved? I'm facing a similar problem.

**Comment by AEnterprise** [comment]
my bad for not responding to this, but i have no clue what the issue could even be, that version does exist: https://github.com/AEnterprise/rsync-deploy/releases/tag/1.0.1

**Comment by jiangxiaoqiang** [comment]
> @jiangxiaoqiang Did you ever get this resolved? I'm facing a similar problem.

I use the 1.0 version, and it works fine. This is the code I am using now:



 ```
   - name: Copy jar to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        # use pre-configured secret (the private key)
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: -avz --delete
        SERVER_PORT: "22"
        # folder to push (./ is the root of current repo)
        FOLDER: ./dolphin-post/dolphin-post-service/build/libs
        SERVER_IP: ${{ secrets.BINGQIAN_HOST }}
        USERNAME: ${{ secrets.BINGQIAN_USER }}
        SERVER_DESTINATION: /opt/apps/dolphin-post

```
