### ISSUE TITLE
100 error when using in pipelines.

### ISSUE THREAD

**Issue by sunscreem** [AEnterprise/rsync-deploy#9]
I can't deploy sites using this repo at the moment as they are failing.

Looks like it might be a problem with debian:

```
 Ign:1 http://deb.debian.org/debian stretch InRelease
  Get:2 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
  Ign:3 http://security.debian.org/debian-security stretch/updates InRelease
  Get:4 http://deb.debian.org/debian stretch Release [118 kB]
  Err:5 http://security.debian.org/debian-security stretch/updates Release
    404  Not Found [IP: 151.101.194.132 80]
  Get:6 http://deb.debian.org/debian stretch Release.gpg [3177 B]
  Get:7 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
  Reading package lists...
  E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
  The command '/bin/sh -c apt update' returned a non-zero code: 100
  ```

**Comment by tohn** [comment]
Run into the same issue. You can use [my fork instead](https://github.com/tohn/rsync-deploy). I'm using the latest alpine image instead of Debian.

**Comment by azusachino** [comment]
Well, switch to debian:stable-slim in the Dockerfile could solve this problem. I forked this repo too, [ref](https://github.com/azusachino/rsync-deploy) .

**Comment by magestacks** [comment]
@tohn @azusachino How about changing the existing configuration?

```yaml
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.AUTO_REFRESH_BLOG_BY_GITHUB_ACTION }}
          ARGS: -avz --delete --exclude='*.pyc'
          SERVER_PORT: '22'
          FOLDER: docs/.vuepress/dist
          SERVER_IP: ${{ secrets.IP }}
          USERNAME: root
          SERVER_DESTINATION: /home
```
